language: php
php:
- 5.5
- 5.6
install:
- composer install
script:
- ./vendor/bin/phing test
after_script:
- if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then ./vendor/bin/coveralls -vvv; fi;
notifications:
  email:
    recipients:
    - kristof@2dotstwice.be
  slack: cnet:UzmZZjVck1RNHTyrTSe6NTd9
