language: php
php:
- 5.5
- 5.6
matrix:
  include:
    - env: udb3version='dev-feature/III-369 as 0.1'
    - env: udb3version='dev-develop as 0.1'
install:
- composer install
- composer require cultuurnet/udb3:${udb3version} --update-with-dependencies
script:
- ./vendor/bin/phpunit
- ./vendor/bin/phing test
after_script:
- ./vendor/bin/coveralls -vvv
notifications:
  email:
    recipients:
    - kristof@2dotstwice.be
