language: php
php:
- 7.1
install:
- composer install
script:
- ./vendor/bin/phing test
after_script:
- ./vendor/bin/coveralls -vvv;
notifications:
  email:
    recipients:
    - kristof@2dotstwice.be
  slack: cnet:UzmZZjVck1RNHTyrTSe6NTd9
