language: php
php:
- 5.5
- 5.6
matrix:
  include:
    - php: 5.6
      env: udb3version='dev-develop as 0.1'
install:
- composer install
- if [ ! -z "$udb3version" ]; then composer require "cultuurnet/udb3:${udb3version}" --ignore-platform-reqs; fi;
script:
- ./vendor/bin/phpunit
- ./vendor/bin/phing test
after_script:
- if [[ "$TRAVIS_PHP_VERSION" = "5.6" && "$udb3version" = "dev-develop as 0.1" ]]; then ./vendor/bin/coveralls -vvv; fi;
notifications:
  email:
    recipients:
    - kristof@2dotstwice.be
